# Generated by Django 4.2.4 on 2023-12-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('is_donated', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/%Y/%m/')),
                ('book_type', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
