# Generated by Django 4.2.4 on 2023-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_book_book_name_alter_book_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_donated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
