# Generated by Django 4.2.4 on 2023-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_is_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='on_sell',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
